=== NCIP/psc/1.5-beta/src/main/java/psc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://bioinformatics.northwestern.edu/ns/psc"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:psc="http://bioinformatics.northwestern.edu/ns/psc"
            xmlns="http://bioinformatics.northwestern.edu/ns/psc"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:element name="studies">
        <xsd:annotation>
            <xsd:documentation>
                A collection of study elements.  Generally, none of the elements that may be
                embedded in a study will occur in the elements nested in studies.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="psc:study"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="study" type="psc:Study" />

    <xsd:complexType name="Study">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="psc:planned-calendar" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="psc:amendment" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="psc:population" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="assigned-identifier" type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- Elements of the template -->

    <xsd:element name="planned-calendar" type="psc:PlannedCalendar"/>

    <xsd:complexType name="PlannedCalendar">
        <xsd:sequence>
            <xsd:element ref="psc:epoch" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:element name="epoch" type="psc:Epoch"/>

    <xsd:complexType name="Epoch">
        <xsd:sequence>
            <xsd:element name="study-segment" type="psc:StudySegment" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:element name="study-segment" type="psc:StudySegment"/>

    <xsd:complexType name="StudySegment">
        <xsd:sequence>
            <xsd:element name="period" type="psc:Period" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:element name="period" type="psc:Period"/>

    <xsd:complexType name="Period">
        <xsd:sequence>
            <xsd:element name="planned-activity" type="psc:PlannedActivity" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="start-day" type="xsd:integer" use="required"/>
        <xsd:attribute name="repetitions" type="xsd:integer" use="required"/>
        <xsd:attribute name="duration-quantity" type="xsd:integer" use="required"/>
        <xsd:attribute name="duration-unit" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:element name="planned-activity" type="psc:PlannedActivity"/> 

    <xsd:complexType name="PlannedActivity">
        <xsd:sequence>
            <xsd:element name="activity" type="psc:Activity"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="day" type="xsd:integer" use="required"/>
        <xsd:attribute name="details" type="xsd:string"/>
        <xsd:attribute name="condition" type="xsd:string"/>
        <xsd:attribute name="population" type="xsd:string"/>
    </xsd:complexType>

    <!-- Elements of amendments (deltas & changes) -->

    <xsd:element name="amendment" type="psc:Amendment"/>

    <xsd:complexType name="Amendment">
        <xsd:sequence>
            <xsd:element name="planned-calendar-delta" type="psc:Delta" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="epoch-delta" type="psc:Delta" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="study-segment-delta" type="psc:Delta" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="period-delta" type="psc:Delta" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="planned-activity-delta" type="psc:Delta" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="date" type="xsd:date" use="required"/>
        <xsd:attribute name="mandatory" type="xsd:boolean" default="true"/>
        <xsd:attribute name="previous-amendment-key" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="Delta">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="add" type="psc:Add" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="remove" type="psc:Remove" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="reorder" type="psc:Reorder" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="property-change" type="psc:PropertyChange" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="node-id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="Add">
        <xsd:choice>
            <xsd:element ref="psc:epoch"/>
            <xsd:element ref="psc:study-segment"/>
            <xsd:element ref="psc:period"/>
            <xsd:element ref="psc:planned-activity"/>
        </xsd:choice>
        <xsd:attribute name="index" type="xsd:integer" use="optional"/>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="Remove">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="child-id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="Reorder">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="child-id" type="xsd:string" use="required"/>
        <xsd:attribute name="old-index" type="xsd:integer" use="required"/>
        <xsd:attribute name="new-index" type="xsd:integer" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="PropertyChange">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="property-name" type="xsd:string" use="required"/>
        <xsd:attribute name="old-value" type="xsd:string" use="required"/>
        <xsd:attribute name="new-value" type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- Elements of global activities -->

    <xsd:element name="sources" type="psc:Sources" />

    <xsd:complexType name="Sources">
        <xsd:sequence>
            <xsd:element name="source" type="psc:Source" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Source">
        <xsd:sequence>
            <xsd:element ref="psc:activity" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>

    <xsd:element name="activity" type="psc:Activity"/>

    <xsd:complexType name="Activity">
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="description" type="xsd:string"/>
        <xsd:attribute name="type-id" type="xsd:integer" use="required"/>
        <xsd:attribute name="code" type="xsd:string"  use="required"/>
        <xsd:attribute name="source" type="xsd:string"/>
    </xsd:complexType>

    <xsd:element name="population" type="psc:Population"/>

    <xsd:complexType name="Population">
        <xsd:attribute name="abbreviation" type="xsd:string" use="required"/>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>

</xsd:schema>

=== NCIP/psc/core/src/main/java/default-activities.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--L
  Copyright Northwestern University.

  Distributed under the OSI-approved BSD 3-Clause License.
  See http://ncip.github.com/psc/LICENSE.txt for details.
L-->

<sources xmlns="http://bioinformatics.northwestern.edu/ns/psc"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://bioinformatics.northwestern.edu/ns/psc http://bioinformatics.northwestern.edu/ns/psc/psc.xsd">
    
<source name="NU Sample Activities">
    <!-- Type 1 Activities -->
    <activity
        name="CT"
        code="CT"
        type-id="1"/>

    <activity
        name="X-Ray"
        code="X-Ray"
        type-id="1"/>

    <activity
        name="Bone Scan"
        code="BoneScan"
        type-id="1"/>

    <activity
        name="Mammogram"
        code="Mammogram"
        type-id="1"/>

    <activity
        name="Ultrasound"
        code="Ultrasound"
        type-id="1"/>

    <activity
        name="CXR"
        code="CXR"
        type-id="1"/>

    <activity
        name="CSF cytology"
        code="CSFCytology"
        type-id="1"/>

    <activity
        name="Tumor Measurement"
        code="TumorMeasurement"
        type-id="1"/>

    <!-- type-id 2 Activities -->
    <activity
        name="Infusion"
        code="Infusion"
        type-id="2"/>

    <activity
        name="Capecitabine"
        code="Capecitabine"
        type-id="2"/>

    <activity
        name="Docetaxel"
        code="Docetaxel"
        type-id="2"/>

    <activity
        name="Peptide Vaccine"
        code=""
        type-id="2"/>

    <activity
        name="Cytoxan Infusion"
        code="CytoxanInfusion"
        type-id="2"/>

    <activity
        name="Adriamycin Infusion"
        code="AdriamycinInfusion"
        type-id="2"/>

    <activity
        name="Taxol Infusion"
        code="TaxolInfusion"
        type-id="2"/>

    <activity
        name="Infusion CPT-11"
        code="InfusionCPT-11"
        type-id="2"/>

    <activity
        name="PBSCT"
        code="PBSCT"
        type-id="2"/>

    <activity
        name="IL-2"
        code="IL-2"
        type-id="2"/>

    <activity
        name="Thalidomide daily"
        code="ThalidomideDaily"
        type-id="2"/>

    <activity
        name="Cyclosphosphamide Tablets"
        code="CyclosphosphamideTablets"
        type-id="2"/>

    <activity
        name="Methotrexate Infusion"
        code="MethotrexateInfusion"
        type-id="2"/>

    <activity
        name="Fluorouracil Infusion"
        code="FluorouracilInfusion"
        type-id="2"/>

    <activity
        name="Cyclosphosphamide Infusion"
        code="CyclosphosphamideInfusion"
        type-id="2"/>

    <activity
        name="Capecitabine Tablets"
        code="CapecitabineTablets"
        type-id="2"/>

    <!-- type-id 3 Activities -->
    <activity
        name="CBC"
        code="CBC"
        type-id="3"/>

    <activity
        name="CK"
        code="CK"
        type-id="3"/>

    <activity
        name="CMP"
        code="CMP"
        type-id="3"/>

    <activity
        name="Plates"
        code="Plates"
        type-id="3"/>

    <activity
        name="PT/PTT"
        code="PT/PTT"
        type-id="3"/>

    <activity
        name="ANA"
        code="ANA"
        type-id="3"/>

    <activity
        name="calcium"
        code="calcium"
        type-id="3"/>

    <activity
        name="Rheumatoid factor"
        code="RheumatoidFactor"
        type-id="3"/>

    <activity
        name="BhCG"
        code="BhCG"
        type-id="3"/>

    <activity
        name="Creatinine kinase"
        code="CreatinineKinase"
        type-id="3"/>

    <activity
        name="Urinalysis"
        code="Urinalysis"
        type-id="3"/>

    <activity
        name="Albumin"
        code="Albumin"
        type-id="3"/>

    <activity
        name="uric acid"
        code="UricAcid"
        type-id="3"/>

    <!-- type-id 4 Activities -->
    <activity
        name="EKG"
        code="EKG"
        type-id="4"/>

    <activity
        name="DTH skin test"
        code="DTHSkinTest"
        type-id="4"/>

    <activity
        name="Physical Exam"
        code="PhysicalExam"
        type-id="4"/>

    <activity
        name="Bone Marrow Biopsy"
        code="BoneMarrowBiopsy"
        type-id="4"/>

    <activity
        name="MUGA or ECHO"
        code="MUGAorECHO"
        type-id="4"/>

    <activity
        name="Height, Weight, Perf Status"
        code="Height,Weight,Perf Status"
        type-id="4"/>

    <activity
        name="Vital signs"
        code="VitalSigns"
        type-id="4"/>

    <activity
        name="LVEF"
        code="LVEF"
        type-id="4"/>

    <activity
        name="Eye Exam"
        code="EyeExam"
        type-id="4"/>

    <!-- type-id 5 Activities -->
    <activity
        name="Quality of Life (QOL)"
        code="QOL"
        type-id="5"/>

    <activity
        name="Mini Mental State Exam (MMSE)"
        code="MMSE"
        type-id="5"/>

    <activity
        name="Diary Entry"
        code="DiaryEntry"
        type-id="5"/>

    <activity
        name="Brief Pain Inventory"
        code="BriefPainInventory"
        type-id="5"/>

    <activity
        name="12 minute walk"
        code="12MinuteWalk"
        type-id="5"/>

    <activity
        name="Rest 14 days"
        code="Rest14Days"
        type-id="5"/>

    <activity
        name="Rest 4 weeks"
        code="Rest4Weeks"
        type-id="5"/>

    <activity
        name="Electronic Telephone Diary"
        code="ElectronicTelephoneDiary"
        type-id="5"/>
    
</source>

</sources>

=== NCIP/psc/test/restful-api/src/spec/resources/templates/every-element.xml
<?xml version="1.0" encoding="UTF-8"?>

<study xmlns="http://bioinformatics.northwestern.edu/ns/psc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" assigned-identifier="every-element" last-modified-date="2010-10-01T13:40:08.36Z" xsi:schemaLocation="http://bioinformatics.northwestern.edu/ns/psc http://bioinformatics.northwestern.edu/ns/psc/psc.xsd">
  <planned-calendar id="EE-PC1"/>
  <amendment name="[Original]" date="2011-11-11" mandatory="true" updated-date="2008-03-18T23:50:03.243Z">
    <planned-calendar-delta id="EE-PCdelta-1" node-id="EE-PC1">
      <add id="EE-PCdelta-1.1" index="0">
        <epoch id="EE-PC1-E1" name="Treatment">
          <study-segment id="EE-PC1-SS1" name="Regimen A">
            <period id="EE-PC1-E1-SS1-P1" repetitions="6" start-day="1" duration-quantity="28" duration-unit="day">
              <planned-activity id="EE-PC1-E1-SS1-P1-PA1" details="Subcutaneously once daily" day="1">
                <label name="pharmacy"/>
                <activity-reference code="100001" source="EE Activities"/>
              </planned-activity>
            </period>
          </study-segment>
        </epoch>
      </add>
    </planned-calendar-delta>
  </amendment>
  <sources>
    <source name="EE Activities">
      <activity name="Azacitidine" code="100001" description="" type="Intervention"/>
    </source>
  </sources>
</study>

=== NCIP/psc/test/restful-api/src/spec/resources/templates/every-delta.xml
<?xml version="1.0" encoding="UTF-8"?>

<study xmlns="http://bioinformatics.northwestern.edu/ns/psc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" assigned-identifier="every-delta" last-modified-date="2010-10-01T13:40:08.36Z" xsi:schemaLocation="http://bioinformatics.northwestern.edu/ns/psc http://bioinformatics.northwestern.edu/ns/psc/psc.xsd">
  <planned-calendar id="ED-PC1"/>
  <amendment name="Change it all" date="2011-12-12" mandatory="true" updated-date="2008-03-19T23:50:03.243Z" previous-amendment-key="2011-11-11~[Original]">
    <epoch-delta id="ED-EDelta1" node-id="ED-PC1-E1">
      <property-change id="ED-EDelta1.1" property-name="name" old-value="Treatment" new-value="Fixing things"/>
      <add id="ED-EDelta1.2" index="1">
        <study-segment id="ED-PC1-E1-SS2" name="Regimen Z">
          <period id="ED-PC1-E1-SS2-P1" repetitions="12" start-day="1" duration-quantity="14" duration-unit="day">
            <planned-activity id="ED-PC1-E1-SS2-P1-PA1" day="1">
              <activity-reference code="100001" source="ED Activities"/>
            </planned-activity>
          </period>
        </study-segment>
      </add>
    </epoch-delta>
    <study-segment-delta id="ED-SSDelta1" node-id="ED-PC1-E1-SS1">
      <property-change id="ED-SSDelta1.1" property-name="name" old-value="Regimen A" new-value="Regimen Alpha"/>
      <add id="ED-SSDelta1.2">
        <period id="ED-PC1-E1-SS1-P2" name="Weekly" repetitions="1" start-day="2" duration-quantity="1" duration-unit="week">
          <planned-activity id="ED-PC1-E1-SS1-P2-PA1" day="2">
            <activity-reference code="100001" source="ED Activities"/>
          </planned-activity>
        </period>
      </add>
    </study-segment-delta>
    <period-delta id="ED-PDelta1" node-id="ED-PC1-E1-SS1-P1">
      <property-change id="ED-PDelta1.1" property-name="name" old-value="" new-value="Sixer"/>
      <add id="ED-PDelta1.2" index="1">
        <planned-activity id="ED-PC1-E1-SS1-P1-PA2" day="2" details="Once again">
          <activity-reference code="100001" source="ED Activities"/>
        </planned-activity>
      </add>
    </period-delta>
    <planned-activity-delta id="ED-PADelta1" node-id="ED-PC1-E1-SS1-P1-PA1">
      <property-change id="ED-PADelta1.1" property-name="details" old-value="Subcutaneously once daily" new-value="Thrice at least"/>
    </planned-activity-delta>
  </amendment>
  <amendment name="[Original]" date="2011-11-11" mandatory="true" updated-date="2008-03-18T23:50:03.243Z">
    <planned-calendar-delta id="ED-PCdelta1" node-id="ED-PC1">
      <add id="ED-PCdelta1.1" index="0">
        <epoch id="ED-PC1-E1" name="Treatment">
          <study-segment id="ED-PC1-E1-SS1" name="Regimen A">
            <period id="ED-PC1-E1-SS1-P1" repetitions="6" start-day="1" duration-quantity="28" duration-unit="day">
              <planned-activity id="ED-PC1-E1-SS1-P1-PA1" details="Subcutaneously once daily" day="1">
                <label name="pharmacy"/>
                <activity-reference code="100001" source="ED Activities"/>
              </planned-activity>
            </period>
          </study-segment>
        </epoch>
      </add>
    </planned-calendar-delta>
  </amendment>
  <sources>
    <source name="ED Activities">
      <activity name="Azacitidine" code="100001" description="" type="Intervention"/>
    </source>
  </sources>
</study>
